
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      micro-service-productos:
        condition: service_healthy
    networks:
      - my-network

  micro-service-productos:
    build:
      context: ./micro-service-productos
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ms_productos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ms_productos
    ports:
      - 3307:3306
    networks:
      - my-network
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: mysqld_safe --datadir=/var/lib/mysql --socket=/tmp/mysql.sock &
    
  crud-react:
    build:
      context: ./crud-react
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    depends_on:
      api-gateway:
        condition: service_healthy
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
